// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	DeleteResource(ctx context.Context, id string) error
	GetResource(ctx context.Context, id string) (Resource, error)
	ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
}

var _ Querier = (*Queries)(nil)
