// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package db

import (
	"context"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (id, name, owner, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, owner, status, created_at
`

type CreateResourceParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Owner  string `json:"owner"`
	Status string `json:"status"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.ID,
		arg.Name,
		arg.Owner,
		arg.Status,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, name, owner, status, created_at FROM resources WHERE id = $1
`

func (q *Queries) GetResource(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, name, owner, status, created_at FROM resources
WHERE ($1::text = '' OR owner = $1::text)
ORDER BY id
LIMIT $2
`

type ListResourcesParams struct {
	Owner     string `json:"owner"`
	PageLimit int32  `json:"page_limit"`
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources, arg.Owner, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Owner,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET name = $2, owner = $3, status = $4
WHERE id = $1
RETURNING id, name, owner, status, created_at
`

type UpdateResourceParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Owner  string `json:"owner"`
	Status string `json:"status"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ID,
		arg.Name,
		arg.Owner,
		arg.Status,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
